#!/bin/bash

# Mapsforge map creation (with coastlines)
# using OpenStreetMap data from Geofabrik
#
# https://github.com/mapsforge/mapsforge/blob/master/docs/MapCreation.md
#
# Written by devemux86

# Configuration

# http://wiki.openstreetmap.org/wiki/Osmosis
[ $OSMOSIS_HOME ] || OSMOSIS_HOME="$HOME/programs/osmosis"

# http://data.openstreetmapdata.com/land-polygons-split-4326.zip
[ $LAND_PATH ] || LAND_PATH="$HOME/mapsforge/land-polygons-split-4326"

[ $DATA_PATH ] || DATA_PATH="$HOME/mapsforge/data"

[ $MAPS_PATH ] || MAPS_PATH="$HOME/mapsforge/maps"

[ $POIS_PATH ] || POIS_PATH="$HOME/mapsforge/pois"

[ $TAG_VALUES ] || TAG_VALUES="false"

# =========== DO NOT CHANGE AFTER THIS LINE. ===========================
# Below here is regular code, part of the file. This is not designed to
# be modified by users.
# ======================================================================

if [ $# -lt 2 ]; then
  echo "Usage: $0 continent/country[/region] ram|hd [lang,...]"
  echo "Example: $0 europe/germany/berlin ram en,de,fr,es"
  exit
fi

cd "$(dirname "$0")"

NAME="$(basename "$1")"

DATA_PATH="$DATA_PATH/$1"
mkdir -p "$DATA_PATH"

if [ "$TAG_VALUES" = "true" ]; then
  MAPS_PATH="$MAPS_PATH/v5"
else
  [ $3 ] && MAPS_PATH="$MAPS_PATH/v4" || MAPS_PATH="$MAPS_PATH/v3"
fi
MAPS_PATH="$(dirname "$MAPS_PATH/$1")"
mkdir -p "$MAPS_PATH"

POIS_PATH="$(dirname "$POIS_PATH/$1")"
mkdir -p "$POIS_PATH"

# Download

wget -nv -N -P "$DATA_PATH" http://download.geofabrik.de/$1-latest.osm.pbf
wget -nv -N -P "$DATA_PATH" http://download.geofabrik.de/$1-latest.osm.pbf.md5
(cd "$DATA_PATH" && exec md5sum -c "$NAME-latest.osm.pbf.md5") || exit 1
wget -nv -N -P "$DATA_PATH" http://download.geofabrik.de/$1.poly

# Bounds

BBOX=$(perl poly2bb.pl "$DATA_PATH/$NAME.poly")
BBOX=(${BBOX//,/ })
BOTTOM=${BBOX[0]}
LEFT=${BBOX[1]}
TOP=${BBOX[2]}
RIGHT=${BBOX[3]}

# Start position

CENTER=$(perl poly2center.pl "$DATA_PATH/$NAME.poly")
CENTER=(${CENTER//,/ })
LAT=${CENTER[0]}
LON=${CENTER[1]}

# Land

ogr2ogr -overwrite -progress -skipfailures -clipsrc $LEFT $BOTTOM $RIGHT $TOP "$DATA_PATH/land.shp" "$LAND_PATH/land_polygons.shp"
python shape2osm.py -l "$DATA_PATH/land" "$DATA_PATH/land.shp"

# Sea

cp sea.osm "$DATA_PATH"
sed -i "s/\$BOTTOM/$BOTTOM/g" "$DATA_PATH/sea.osm"
sed -i "s/\$LEFT/$LEFT/g" "$DATA_PATH/sea.osm"
sed -i "s/\$TOP/$TOP/g" "$DATA_PATH/sea.osm"
sed -i "s/\$RIGHT/$RIGHT/g" "$DATA_PATH/sea.osm"

# Merge

"$OSMOSIS_HOME/bin/osmosis" --rb file="$DATA_PATH/$NAME-latest.osm.pbf" \
                            --rx file="$DATA_PATH/sea.osm" --s --m \
                            --rx file="$DATA_PATH/land.osm" --s --m \
                            --wb file="$DATA_PATH/merge.pbf" omitmetadata=true

# Map

if [ "$SKIP_MAP_CREATION" != "true" ]; then
  CMD="$OSMOSIS_HOME/bin/osmosis --rb file=$DATA_PATH/merge.pbf \
                                 --mw file=$MAPS_PATH/$NAME.map \
                                      type=$2 \
                                      bbox=$BOTTOM,$LEFT,$TOP,$RIGHT \
                                      map-start-position=$LAT,$LON \
                                      map-start-zoom=8 \
                                      tag-values=$TAG_VALUES"
  [ $3 ] && CMD="$CMD preferred-languages=$3"
  [ $MAP_TAG_CONF_FILE ] && CMD="$CMD tag-conf-file=$MAP_TAG_CONF_FILE"
  echo $CMD
  if ! $CMD ; then
    exit 1
  fi
fi

# POI

if [ "$SKIP_POI_CREATION" != "true" ]; then
  CMD="$OSMOSIS_HOME/bin/osmosis --rb file=$DATA_PATH/$NAME-latest.osm.pbf \
                                 --pw file=$POIS_PATH/$NAME.poi"
  [ $POI_TAG_CONF_FILE ] && CMD="$CMD tag-conf-file=$POI_TAG_CONF_FILE"
  echo $CMD
  if ! $CMD ; then
    exit 1
  fi
fi 
