#!/bin/bash

cd "$(dirname "$0")"

../map-creator africa/algeria ram
../map-creator africa/angola ram
../map-creator africa/benin ram
../map-creator africa/botswana ram
../map-creator africa/burkina-faso ram
../map-creator africa/burundi ram
../map-creator africa/cameroon ram
../map-creator africa/canary-islands ram
../map-creator africa/cape-verde ram
../map-creator africa/central-african-republic ram
../map-creator africa/chad ram
../map-creator africa/comores ram
../map-creator africa/congo-brazzaville ram
../map-creator africa/congo-democratic-republic ram
../map-creator africa/djibouti ram
../map-creator africa/egypt ram
../map-creator africa/equatorial-guinea ram
../map-creator africa/eritrea ram
../map-creator africa/ethiopia ram
../map-creator africa/gabon ram
../map-creator africa/ghana ram
../map-creator africa/guinea ram
../map-creator africa/guinea-bissau ram
../map-creator africa/ivory-coast ram
../map-creator africa/kenya ram
../map-creator africa/lesotho ram
../map-creator africa/liberia ram
../map-creator africa/libya ram
../map-creator africa/madagascar ram
../map-creator africa/malawi ram
../map-creator africa/mali ram
../map-creator africa/mauritania ram
../map-creator africa/mauritius ram
../map-creator africa/morocco ram
../map-creator africa/mozambique ram
../map-creator africa/namibia ram
../map-creator africa/niger ram
../map-creator africa/nigeria ram
../map-creator africa/rwanda ram
../map-creator africa/saint-helena-ascension-and-tristan-da-cunha ram
../map-creator africa/sao-tome-and-principe ram
../map-creator africa/senegal-and-gambia ram
../map-creator africa/seychelles ram
../map-creator africa/sierra-leone ram
../map-creator africa/somalia ram
../map-creator africa/south-africa-and-lesotho ram
../map-creator africa/south-sudan ram
../map-creator africa/sudan ram
../map-creator africa/swaziland ram
../map-creator africa/tanzania ram
../map-creator africa/togo ram
../map-creator africa/tunisia ram
../map-creator africa/uganda ram
../map-creator africa/zambia ram
../map-creator africa/zimbabwe ram
