#!/bin/bash

cd "$(dirname "$0")"

../map-creator.sh africa/algeria ram
../map-creator.sh africa/angola ram
../map-creator.sh africa/benin ram
../map-creator.sh africa/botswana ram
../map-creator.sh africa/burkina-faso ram
../map-creator.sh africa/burundi ram
../map-creator.sh africa/cameroon ram
../map-creator.sh africa/canary-islands ram
../map-creator.sh africa/cape-verde ram
../map-creator.sh africa/central-african-republic ram
../map-creator.sh africa/chad ram
../map-creator.sh africa/comores ram
../map-creator.sh africa/congo-brazzaville ram
../map-creator.sh africa/congo-democratic-republic ram
../map-creator.sh africa/djibouti ram
../map-creator.sh africa/egypt ram
../map-creator.sh africa/equatorial-guinea ram
../map-creator.sh africa/eritrea ram
../map-creator.sh africa/ethiopia ram
../map-creator.sh africa/gabon ram
../map-creator.sh africa/ghana ram
../map-creator.sh africa/guinea ram
../map-creator.sh africa/guinea-bissau ram
../map-creator.sh africa/ivory-coast ram
../map-creator.sh africa/kenya ram
../map-creator.sh africa/lesotho ram
../map-creator.sh africa/liberia ram
../map-creator.sh africa/libya ram
../map-creator.sh africa/madagascar ram
../map-creator.sh africa/malawi ram
../map-creator.sh africa/mali ram
../map-creator.sh africa/mauritania ram
../map-creator.sh africa/mauritius ram
../map-creator.sh africa/morocco ram
../map-creator.sh africa/mozambique ram
../map-creator.sh africa/namibia ram
../map-creator.sh africa/niger ram
../map-creator.sh africa/nigeria ram
../map-creator.sh africa/rwanda ram
../map-creator.sh africa/saint-helena-ascension-and-tristan-da-cunha ram
../map-creator.sh africa/sao-tome-and-principe ram
../map-creator.sh africa/senegal-and-gambia ram
../map-creator.sh africa/seychelles ram
../map-creator.sh africa/sierra-leone ram
../map-creator.sh africa/somalia ram
../map-creator.sh africa/south-africa-and-lesotho ram
../map-creator.sh africa/south-sudan ram
../map-creator.sh africa/sudan ram
../map-creator.sh africa/swaziland ram
../map-creator.sh africa/tanzania ram
../map-creator.sh africa/togo ram
../map-creator.sh africa/tunisia ram
../map-creator.sh africa/uganda ram
../map-creator.sh africa/zambia ram
../map-creator.sh africa/zimbabwe ram
