#!/bin/bash

cd "$(dirname "$0")"

../map-creator.sh asia/afghanistan ram
../map-creator.sh asia/armenia ram
../map-creator.sh asia/azerbaijan ram
../map-creator.sh asia/bangladesh ram
../map-creator.sh asia/bhutan ram
../map-creator.sh asia/cambodia ram
../map-creator.sh asia/china ram
../map-creator.sh asia/gcc-states ram
../map-creator.sh asia/india ram
../map-creator.sh asia/indonesia ram
../map-creator.sh asia/iran ram
../map-creator.sh asia/iraq ram
../map-creator.sh asia/israel-and-palestine ram
../map-creator.sh asia/japan hd
../map-creator.sh asia/jordan ram
../map-creator.sh asia/kazakhstan ram
../map-creator.sh asia/kyrgyzstan ram
../map-creator.sh asia/laos ram
../map-creator.sh asia/lebanon ram
../map-creator.sh asia/malaysia-singapore-brunei ram
../map-creator.sh asia/maldives ram
../map-creator.sh asia/mongolia ram
../map-creator.sh asia/myanmar ram
../map-creator.sh asia/nepal ram
../map-creator.sh asia/north-korea ram
../map-creator.sh asia/pakistan ram
../map-creator.sh asia/philippines ram
../map-creator.sh asia/south-korea ram
../map-creator.sh asia/sri-lanka ram
../map-creator.sh asia/syria ram
../map-creator.sh asia/taiwan ram
../map-creator.sh asia/tajikistan ram
../map-creator.sh asia/thailand ram
../map-creator.sh asia/turkmenistan ram
../map-creator.sh asia/uzbekistan ram
../map-creator.sh asia/vietnam ram
../map-creator.sh asia/yemen ram
