#!/bin/bash

cd "$(dirname "$0")"

../map-creator central-america/belize ram
../map-creator central-america/cuba ram
../map-creator central-america/guatemala ram
../map-creator central-america/haiti-and-domrep ram
../map-creator central-america/nicaragua ram
