#!/bin/bash

cd "$(dirname "$0")"

../map-creator.sh europe/albania ram
../map-creator.sh europe/alps hd
../map-creator.sh europe/andorra ram
../map-creator.sh europe/austria ram
../map-creator.sh europe/azores ram
../map-creator.sh europe/belarus ram
../map-creator.sh europe/belgium ram
../map-creator.sh europe/bosnia-herzegovina ram
../map-creator.sh europe/bulgaria ram
../map-creator.sh europe/croatia ram
../map-creator.sh europe/cyprus ram
../map-creator.sh europe/czech-republic ram
../map-creator.sh europe/denmark ram
../map-creator.sh europe/estonia ram
../map-creator.sh europe/faroe-islands ram
../map-creator.sh europe/finland ram
../map-creator.sh europe/france hd
../map-creator.sh europe/georgia ram
../map-creator.sh europe/germany hd
../map-creator.sh europe/great-britain ram
../map-creator.sh europe/greece ram
../map-creator.sh europe/hungary ram
../map-creator.sh europe/iceland ram
../map-creator.sh europe/ireland-and-northern-ireland ram
../map-creator.sh europe/isle-of-man ram
../map-creator.sh europe/italy hd
../map-creator.sh europe/kosovo ram
../map-creator.sh europe/latvia ram
../map-creator.sh europe/liechtenstein ram
../map-creator.sh europe/lithuania ram
../map-creator.sh europe/luxembourg ram
../map-creator.sh europe/macedonia ram
../map-creator.sh europe/malta ram
../map-creator.sh europe/moldova ram
../map-creator.sh europe/monaco ram
../map-creator.sh europe/montenegro ram
../map-creator.sh europe/netherlands hd
../map-creator.sh europe/norway hd
../map-creator.sh europe/poland hd
../map-creator.sh europe/portugal ram
../map-creator.sh europe/romania ram
../map-creator.sh europe/serbia ram
../map-creator.sh europe/slovakia ram
../map-creator.sh europe/slovenia ram
../map-creator.sh europe/spain ram
../map-creator.sh europe/sweden ram
../map-creator.sh europe/switzerland ram
../map-creator.sh europe/turkey ram
../map-creator.sh europe/ukraine ram
