#!/bin/bash

cd "$(dirname "$0")"

../map-creator north-america/us/alabama ram
../map-creator north-america/us/alaska ram
../map-creator north-america/us/arizona ram
../map-creator north-america/us/arkansas ram
../map-creator north-america/us/california ram
../map-creator north-america/us/colorado ram
../map-creator north-america/us/connecticut ram
../map-creator north-america/us/delaware ram
../map-creator north-america/us/district-of-columbia ram
../map-creator north-america/us/florida ram
../map-creator north-america/us/georgia ram
../map-creator north-america/us/hawaii ram
../map-creator north-america/us/idaho ram
../map-creator north-america/us/illinois ram
../map-creator north-america/us/indiana ram
../map-creator north-america/us/iowa ram
../map-creator north-america/us/kansas ram
../map-creator north-america/us/kentucky ram
../map-creator north-america/us/louisiana ram
../map-creator north-america/us/maine ram
../map-creator north-america/us/maryland ram
../map-creator north-america/us/massachusetts ram
../map-creator north-america/us/michigan ram
../map-creator north-america/us/minnesota ram
../map-creator north-america/us/mississippi ram
../map-creator north-america/us/missouri ram
../map-creator north-america/us/montana ram
../map-creator north-america/us/nebraska ram
../map-creator north-america/us/nevada ram
../map-creator north-america/us/new-hampshire ram
../map-creator north-america/us/new-jersey ram
../map-creator north-america/us/new-mexico ram
../map-creator north-america/us/new-york ram
../map-creator north-america/us/north-carolina ram
../map-creator north-america/us/north-dakota ram
../map-creator north-america/us/ohio ram
../map-creator north-america/us/oklahoma ram
../map-creator north-america/us/oregon ram
../map-creator north-america/us/pennsylvania ram
../map-creator north-america/us/puerto-rico ram
../map-creator north-america/us/rhode-island ram
../map-creator north-america/us/south-carolina ram
../map-creator north-america/us/south-dakota ram
../map-creator north-america/us/tennessee ram
../map-creator north-america/us/texas ram
../map-creator north-america/us/utah ram
../map-creator north-america/us/vermont ram
../map-creator north-america/us/virginia ram
../map-creator north-america/us/washington ram
../map-creator north-america/us/west-virginia ram
../map-creator north-america/us/wisconsin ram
../map-creator north-america/us/wyoming ram
