#!/bin/bash

cd "$(dirname "$0")"

../map-creator south-america/argentina ram
../map-creator south-america/bolivia ram
../map-creator south-america/brazil ram
../map-creator south-america/chile ram
../map-creator south-america/colombia ram
../map-creator south-america/ecuador ram
../map-creator south-america/paraguay ram
../map-creator south-america/peru ram
../map-creator south-america/suriname ram
../map-creator south-america/uruguay ram
