#!/bin/bash

cd "$(dirname "$0")"

../map-creator africa/algeria ram en,de,fr,es
../map-creator africa/angola ram en,de,fr,es
../map-creator africa/benin ram en,de,fr,es
../map-creator africa/botswana ram en,de,fr,es
../map-creator africa/burkina-faso ram en,de,fr,es
../map-creator africa/burundi ram en,de,fr,es
../map-creator africa/cameroon ram en,de,fr,es
../map-creator africa/canary-islands ram en,de,fr,es
../map-creator africa/cape-verde ram en,de,fr,es
../map-creator africa/central-african-republic ram en,de,fr,es
../map-creator africa/chad ram en,de,fr,es
../map-creator africa/comores ram en,de,fr,es
../map-creator africa/congo-brazzaville ram en,de,fr,es
../map-creator africa/congo-democratic-republic ram en,de,fr,es
../map-creator africa/djibouti ram en,de,fr,es
../map-creator africa/egypt ram en,de,fr,es
../map-creator africa/equatorial-guinea ram en,de,fr,es
../map-creator africa/eritrea ram en,de,fr,es
../map-creator africa/ethiopia ram en,de,fr,es
../map-creator africa/gabon ram en,de,fr,es
../map-creator africa/ghana ram en,de,fr,es
../map-creator africa/guinea ram en,de,fr,es
../map-creator africa/guinea-bissau ram en,de,fr,es
../map-creator africa/ivory-coast ram en,de,fr,es
../map-creator africa/kenya ram en,de,fr,es
../map-creator africa/lesotho ram en,de,fr,es
../map-creator africa/liberia ram en,de,fr,es
../map-creator africa/libya ram en,de,fr,es
../map-creator africa/madagascar ram en,de,fr,es
../map-creator africa/malawi ram en,de,fr,es
../map-creator africa/mali ram en,de,fr,es
../map-creator africa/mauritania ram en,de,fr,es
../map-creator africa/mauritius ram en,de,fr,es
../map-creator africa/morocco ram en,de,fr,es
../map-creator africa/mozambique ram en,de,fr,es
../map-creator africa/namibia ram en,de,fr,es
../map-creator africa/niger ram en,de,fr,es
../map-creator africa/nigeria ram en,de,fr,es
../map-creator africa/rwanda ram en,de,fr,es
../map-creator africa/saint-helena-ascension-and-tristan-da-cunha ram en,de,fr,es
../map-creator africa/sao-tome-and-principe ram en,de,fr,es
../map-creator africa/senegal-and-gambia ram en,de,fr,es
../map-creator africa/seychelles ram en,de,fr,es
../map-creator africa/sierra-leone ram en,de,fr,es
../map-creator africa/somalia ram en,de,fr,es
../map-creator africa/south-africa-and-lesotho ram en,de,fr,es
../map-creator africa/south-sudan ram en,de,fr,es
../map-creator africa/sudan ram en,de,fr,es
../map-creator africa/swaziland ram en,de,fr,es
../map-creator africa/tanzania ram en,de,fr,es
../map-creator africa/togo ram en,de,fr,es
../map-creator africa/tunisia ram en,de,fr,es
../map-creator africa/uganda ram en,de,fr,es
../map-creator africa/zambia ram en,de,fr,es
../map-creator africa/zimbabwe ram en,de,fr,es
