#!/bin/bash

cd "$(dirname "$0")"

../map-creator.sh africa/algeria ram en,de,fr,es
../map-creator.sh africa/angola ram en,de,fr,es
../map-creator.sh africa/benin ram en,de,fr,es
../map-creator.sh africa/botswana ram en,de,fr,es
../map-creator.sh africa/burkina-faso ram en,de,fr,es
../map-creator.sh africa/burundi ram en,de,fr,es
../map-creator.sh africa/cameroon ram en,de,fr,es
../map-creator.sh africa/canary-islands ram en,de,fr,es
../map-creator.sh africa/cape-verde ram en,de,fr,es
../map-creator.sh africa/central-african-republic ram en,de,fr,es
../map-creator.sh africa/chad ram en,de,fr,es
../map-creator.sh africa/comores ram en,de,fr,es
../map-creator.sh africa/congo-brazzaville ram en,de,fr,es
../map-creator.sh africa/congo-democratic-republic ram en,de,fr,es
../map-creator.sh africa/djibouti ram en,de,fr,es
../map-creator.sh africa/egypt ram en,de,fr,es
../map-creator.sh africa/equatorial-guinea ram en,de,fr,es
../map-creator.sh africa/eritrea ram en,de,fr,es
../map-creator.sh africa/ethiopia ram en,de,fr,es
../map-creator.sh africa/gabon ram en,de,fr,es
../map-creator.sh africa/ghana ram en,de,fr,es
../map-creator.sh africa/guinea ram en,de,fr,es
../map-creator.sh africa/guinea-bissau ram en,de,fr,es
../map-creator.sh africa/ivory-coast ram en,de,fr,es
../map-creator.sh africa/kenya ram en,de,fr,es
../map-creator.sh africa/lesotho ram en,de,fr,es
../map-creator.sh africa/liberia ram en,de,fr,es
../map-creator.sh africa/libya ram en,de,fr,es
../map-creator.sh africa/madagascar ram en,de,fr,es
../map-creator.sh africa/malawi ram en,de,fr,es
../map-creator.sh africa/mali ram en,de,fr,es
../map-creator.sh africa/mauritania ram en,de,fr,es
../map-creator.sh africa/mauritius ram en,de,fr,es
../map-creator.sh africa/morocco ram en,de,fr,es
../map-creator.sh africa/mozambique ram en,de,fr,es
../map-creator.sh africa/namibia ram en,de,fr,es
../map-creator.sh africa/niger ram en,de,fr,es
../map-creator.sh africa/nigeria ram en,de,fr,es
../map-creator.sh africa/rwanda ram en,de,fr,es
../map-creator.sh africa/saint-helena-ascension-and-tristan-da-cunha ram en,de,fr,es
../map-creator.sh africa/sao-tome-and-principe ram en,de,fr,es
../map-creator.sh africa/senegal-and-gambia ram en,de,fr,es
../map-creator.sh africa/seychelles ram en,de,fr,es
../map-creator.sh africa/sierra-leone ram en,de,fr,es
../map-creator.sh africa/somalia ram en,de,fr,es
../map-creator.sh africa/south-africa-and-lesotho ram en,de,fr,es
../map-creator.sh africa/south-sudan ram en,de,fr,es
../map-creator.sh africa/sudan ram en,de,fr,es
../map-creator.sh africa/swaziland ram en,de,fr,es
../map-creator.sh africa/tanzania ram en,de,fr,es
../map-creator.sh africa/togo ram en,de,fr,es
../map-creator.sh africa/tunisia ram en,de,fr,es
../map-creator.sh africa/uganda ram en,de,fr,es
../map-creator.sh africa/zambia ram en,de,fr,es
../map-creator.sh africa/zimbabwe ram en,de,fr,es
