#!/bin/bash

cd "$(dirname "$0")"

../map-creator australia-oceania/australia ram en,de,fr,es
../map-creator australia-oceania/fiji ram en,de,fr,es
../map-creator australia-oceania/new-caledonia ram en,de,fr,es
../map-creator australia-oceania/new-zealand ram en,de,fr,es
../map-creator australia-oceania/papua-new-guinea ram en,de,fr,es
