#!/bin/bash

cd "$(dirname "$0")"

../map-creator.sh europe/albania ram en,de,fr,es
../map-creator.sh europe/alps hd en,de,fr,es
../map-creator.sh europe/andorra ram en,de,fr,es
../map-creator.sh europe/austria ram en,de,fr,es
../map-creator.sh europe/azores ram en,de,fr,es
../map-creator.sh europe/belarus ram en,de,fr,es
../map-creator.sh europe/belgium ram en,de,fr,es
../map-creator.sh europe/bosnia-herzegovina ram en,de,fr,es
../map-creator.sh europe/bulgaria ram en,de,fr,es
../map-creator.sh europe/croatia ram en,de,fr,es
../map-creator.sh europe/cyprus ram en,de,fr,es
../map-creator.sh europe/czech-republic ram en,de,fr,es
../map-creator.sh europe/denmark ram en,de,fr,es
../map-creator.sh europe/estonia ram en,de,fr,es
../map-creator.sh europe/faroe-islands ram en,de,fr,es
../map-creator.sh europe/finland ram en,de,fr,es
../map-creator.sh europe/france hd en,de,fr,es
../map-creator.sh europe/georgia ram en,de,fr,es
../map-creator.sh europe/germany hd en,de,fr,es
../map-creator.sh europe/great-britain ram en,de,fr,es
../map-creator.sh europe/greece ram en,de,fr,es
../map-creator.sh europe/guernsey-jersey ram en,de,fr,es
../map-creator.sh europe/hungary ram en,de,fr,es
../map-creator.sh europe/iceland ram en,de,fr,es
../map-creator.sh europe/ireland-and-northern-ireland ram en,de,fr,es
../map-creator.sh europe/isle-of-man ram en,de,fr,es
../map-creator.sh europe/italy hd en,de,fr,es
../map-creator.sh europe/kosovo ram en,de,fr,es
../map-creator.sh europe/latvia ram en,de,fr,es
../map-creator.sh europe/liechtenstein ram en,de,fr,es
../map-creator.sh europe/lithuania ram en,de,fr,es
../map-creator.sh europe/luxembourg ram en,de,fr,es
../map-creator.sh europe/macedonia ram en,de,fr,es
../map-creator.sh europe/malta ram en,de,fr,es
../map-creator.sh europe/moldova ram en,de,fr,es
../map-creator.sh europe/monaco ram en,de,fr,es
../map-creator.sh europe/montenegro ram en,de,fr,es
../map-creator.sh europe/netherlands hd en,de,fr,es
../map-creator.sh europe/norway hd en,de,fr,es
../map-creator.sh europe/poland hd en,de,fr,es
../map-creator.sh europe/portugal ram en,de,fr,es
../map-creator.sh europe/romania ram en,de,fr,es
../map-creator.sh europe/serbia ram en,de,fr,es
../map-creator.sh europe/slovakia ram en,de,fr,es
../map-creator.sh europe/slovenia ram en,de,fr,es
../map-creator.sh europe/spain ram en,de,fr,es
../map-creator.sh europe/sweden ram en,de,fr,es
../map-creator.sh europe/switzerland ram en,de,fr,es
../map-creator.sh europe/turkey ram en,de,fr,es
../map-creator.sh europe/ukraine ram en,de,fr,es
