#!/bin/bash

cd "$(dirname "$0")"

../map-creator europe/albania ram en,de,fr,es
../map-creator europe/alps hd en,de,fr,es
../map-creator europe/andorra ram en,de,fr,es
../map-creator europe/austria ram en,de,fr,es
../map-creator europe/azores ram en,de,fr,es
../map-creator europe/belarus ram en,de,fr,es
../map-creator europe/belgium ram en,de,fr,es
../map-creator europe/bosnia-herzegovina ram en,de,fr,es
../map-creator europe/bulgaria ram en,de,fr,es
../map-creator europe/croatia ram en,de,fr,es
../map-creator europe/cyprus ram en,de,fr,es
../map-creator europe/czech-republic ram en,de,fr,es
../map-creator europe/denmark ram en,de,fr,es
../map-creator europe/estonia ram en,de,fr,es
../map-creator europe/faroe-islands ram en,de,fr,es
../map-creator europe/finland ram en,de,fr,es
../map-creator europe/france hd en,de,fr,es
../map-creator europe/georgia ram en,de,fr,es
../map-creator europe/germany hd en,de,fr,es
../map-creator europe/great-britain ram en,de,fr,es
../map-creator europe/greece ram en,de,fr,es
../map-creator europe/hungary ram en,de,fr,es
../map-creator europe/iceland ram en,de,fr,es
../map-creator europe/ireland-and-northern-ireland ram en,de,fr,es
../map-creator europe/isle-of-man ram en,de,fr,es
../map-creator europe/italy hd en,de,fr,es
../map-creator europe/kosovo ram en,de,fr,es
../map-creator europe/latvia ram en,de,fr,es
../map-creator europe/liechtenstein ram en,de,fr,es
../map-creator europe/lithuania ram en,de,fr,es
../map-creator europe/luxembourg ram en,de,fr,es
../map-creator europe/macedonia ram en,de,fr,es
../map-creator europe/malta ram en,de,fr,es
../map-creator europe/moldova ram en,de,fr,es
../map-creator europe/monaco ram en,de,fr,es
../map-creator europe/montenegro ram en,de,fr,es
../map-creator europe/netherlands hd en,de,fr,es
../map-creator europe/norway ram en,de,fr,es
../map-creator europe/poland hd en,de,fr,es
../map-creator europe/portugal ram en,de,fr,es
../map-creator europe/romania ram en,de,fr,es
../map-creator europe/serbia ram en,de,fr,es
../map-creator europe/slovakia ram en,de,fr,es
../map-creator europe/slovenia ram en,de,fr,es
../map-creator europe/spain ram en,de,fr,es
../map-creator europe/sweden ram en,de,fr,es
../map-creator europe/switzerland ram en,de,fr,es
../map-creator europe/turkey ram en,de,fr,es
../map-creator europe/ukraine ram en,de,fr,es
