#!/bin/bash

cd "$(dirname "$0")"

../map-creator north-america/us/alabama ram en,de,fr,es
../map-creator north-america/us/alaska ram en,de,fr,es
../map-creator north-america/us/arizona ram en,de,fr,es
../map-creator north-america/us/arkansas ram en,de,fr,es
../map-creator north-america/us/california ram en,de,fr,es
../map-creator north-america/us/colorado ram en,de,fr,es
../map-creator north-america/us/connecticut ram en,de,fr,es
../map-creator north-america/us/delaware ram en,de,fr,es
../map-creator north-america/us/district-of-columbia ram en,de,fr,es
../map-creator north-america/us/florida ram en,de,fr,es
../map-creator north-america/us/georgia ram en,de,fr,es
../map-creator north-america/us/hawaii ram en,de,fr,es
../map-creator north-america/us/idaho ram en,de,fr,es
../map-creator north-america/us/illinois ram en,de,fr,es
../map-creator north-america/us/indiana ram en,de,fr,es
../map-creator north-america/us/iowa ram en,de,fr,es
../map-creator north-america/us/kansas ram en,de,fr,es
../map-creator north-america/us/kentucky ram en,de,fr,es
../map-creator north-america/us/louisiana ram en,de,fr,es
../map-creator north-america/us/maine ram en,de,fr,es
../map-creator north-america/us/maryland ram en,de,fr,es
../map-creator north-america/us/massachusetts ram en,de,fr,es
../map-creator north-america/us/michigan ram en,de,fr,es
../map-creator north-america/us/minnesota ram en,de,fr,es
../map-creator north-america/us/mississippi ram en,de,fr,es
../map-creator north-america/us/missouri ram en,de,fr,es
../map-creator north-america/us/montana ram en,de,fr,es
../map-creator north-america/us/nebraska ram en,de,fr,es
../map-creator north-america/us/nevada ram en,de,fr,es
../map-creator north-america/us/new-hampshire ram en,de,fr,es
../map-creator north-america/us/new-jersey ram en,de,fr,es
../map-creator north-america/us/new-mexico ram en,de,fr,es
../map-creator north-america/us/new-york ram en,de,fr,es
../map-creator north-america/us/north-carolina ram en,de,fr,es
../map-creator north-america/us/north-dakota ram en,de,fr,es
../map-creator north-america/us/ohio ram en,de,fr,es
../map-creator north-america/us/oklahoma ram en,de,fr,es
../map-creator north-america/us/oregon ram en,de,fr,es
../map-creator north-america/us/pennsylvania ram en,de,fr,es
../map-creator north-america/us/puerto-rico ram en,de,fr,es
../map-creator north-america/us/rhode-island ram en,de,fr,es
../map-creator north-america/us/south-carolina ram en,de,fr,es
../map-creator north-america/us/south-dakota ram en,de,fr,es
../map-creator north-america/us/tennessee ram en,de,fr,es
../map-creator north-america/us/texas ram en,de,fr,es
../map-creator north-america/us/utah ram en,de,fr,es
../map-creator north-america/us/vermont ram en,de,fr,es
../map-creator north-america/us/virginia ram en,de,fr,es
../map-creator north-america/us/washington ram en,de,fr,es
../map-creator north-america/us/west-virginia ram en,de,fr,es
../map-creator north-america/us/wisconsin ram en,de,fr,es
../map-creator north-america/us/wyoming ram en,de,fr,es
