#!/bin/bash

cd "$(dirname "$0")"

../map-creator.sh africa/algeria ram en,nl,fr,de,it,es
../map-creator.sh africa/angola ram en,nl,fr,de,it,es
../map-creator.sh africa/benin ram en,nl,fr,de,it,es
../map-creator.sh africa/botswana ram en,nl,fr,de,it,es
../map-creator.sh africa/burkina-faso ram en,nl,fr,de,it,es
../map-creator.sh africa/burundi ram en,nl,fr,de,it,es
../map-creator.sh africa/cameroon ram en,nl,fr,de,it,es
../map-creator.sh africa/canary-islands ram en,nl,fr,de,it,es
../map-creator.sh africa/cape-verde ram en,nl,fr,de,it,es
../map-creator.sh africa/central-african-republic ram en,nl,fr,de,it,es
../map-creator.sh africa/chad ram en,nl,fr,de,it,es
../map-creator.sh africa/comores ram en,nl,fr,de,it,es
../map-creator.sh africa/congo-brazzaville ram en,nl,fr,de,it,es
../map-creator.sh africa/congo-democratic-republic ram en,nl,fr,de,it,es
../map-creator.sh africa/djibouti ram en,nl,fr,de,it,es
../map-creator.sh africa/egypt ram en,nl,fr,de,it,es
../map-creator.sh africa/equatorial-guinea ram en,nl,fr,de,it,es
../map-creator.sh africa/eritrea ram en,nl,fr,de,it,es
../map-creator.sh africa/ethiopia ram en,nl,fr,de,it,es
../map-creator.sh africa/gabon ram en,nl,fr,de,it,es
../map-creator.sh africa/ghana ram en,nl,fr,de,it,es
../map-creator.sh africa/guinea ram en,nl,fr,de,it,es
../map-creator.sh africa/guinea-bissau ram en,nl,fr,de,it,es
../map-creator.sh africa/ivory-coast ram en,nl,fr,de,it,es
../map-creator.sh africa/kenya ram en,nl,fr,de,it,es
../map-creator.sh africa/lesotho ram en,nl,fr,de,it,es
../map-creator.sh africa/liberia ram en,nl,fr,de,it,es
../map-creator.sh africa/libya ram en,nl,fr,de,it,es
../map-creator.sh africa/madagascar ram en,nl,fr,de,it,es
../map-creator.sh africa/malawi ram en,nl,fr,de,it,es
../map-creator.sh africa/mali ram en,nl,fr,de,it,es
../map-creator.sh africa/mauritania ram en,nl,fr,de,it,es
../map-creator.sh africa/mauritius ram en,nl,fr,de,it,es
../map-creator.sh africa/morocco ram en,nl,fr,de,it,es
../map-creator.sh africa/mozambique ram en,nl,fr,de,it,es
../map-creator.sh africa/namibia ram en,nl,fr,de,it,es
../map-creator.sh africa/niger ram en,nl,fr,de,it,es
../map-creator.sh africa/nigeria ram en,nl,fr,de,it,es
../map-creator.sh africa/rwanda ram en,nl,fr,de,it,es
../map-creator.sh africa/saint-helena-ascension-and-tristan-da-cunha ram en,nl,fr,de,it,es
../map-creator.sh africa/sao-tome-and-principe ram en,nl,fr,de,it,es
../map-creator.sh africa/senegal-and-gambia ram en,nl,fr,de,it,es
../map-creator.sh africa/seychelles ram en,nl,fr,de,it,es
../map-creator.sh africa/sierra-leone ram en,nl,fr,de,it,es
../map-creator.sh africa/somalia ram en,nl,fr,de,it,es
../map-creator.sh africa/south-africa-and-lesotho ram en,nl,fr,de,it,es
../map-creator.sh africa/south-sudan ram en,nl,fr,de,it,es
../map-creator.sh africa/sudan ram en,nl,fr,de,it,es
../map-creator.sh africa/swaziland ram en,nl,fr,de,it,es
../map-creator.sh africa/tanzania ram en,nl,fr,de,it,es
../map-creator.sh africa/togo ram en,nl,fr,de,it,es
../map-creator.sh africa/tunisia ram en,nl,fr,de,it,es
../map-creator.sh africa/uganda ram en,nl,fr,de,it,es
../map-creator.sh africa/zambia ram en,nl,fr,de,it,es
../map-creator.sh africa/zimbabwe ram en,nl,fr,de,it,es
