#!/bin/bash

cd "$(dirname "$0")"

../map-creator.sh europe/albania ram en,nl,fr,de,it,es
../map-creator.sh europe/alps hd en,nl,fr,de,it,es
../map-creator.sh europe/andorra ram en,nl,fr,de,it,es
../map-creator.sh europe/austria ram en,nl,fr,de,it,es
../map-creator.sh europe/azores ram en,nl,fr,de,it,es
../map-creator.sh europe/belarus ram en,nl,fr,de,it,es
../map-creator.sh europe/belgium ram en,nl,fr,de,it,es
../map-creator.sh europe/bosnia-herzegovina ram en,nl,fr,de,it,es
../map-creator.sh europe/bulgaria ram en,nl,fr,de,it,es
../map-creator.sh europe/croatia ram en,nl,fr,de,it,es
../map-creator.sh europe/cyprus ram en,nl,fr,de,it,es
../map-creator.sh europe/czech-republic ram en,nl,fr,de,it,es
../map-creator.sh europe/denmark ram en,nl,fr,de,it,es
../map-creator.sh europe/estonia ram en,nl,fr,de,it,es
../map-creator.sh europe/faroe-islands ram en,nl,fr,de,it,es
../map-creator.sh europe/finland ram en,nl,fr,de,it,es
../map-creator.sh europe/france hd en,nl,fr,de,it,es
../map-creator.sh europe/georgia ram en,nl,fr,de,it,es
../map-creator.sh europe/germany hd en,nl,fr,de,it,es
../map-creator.sh europe/great-britain ram en,nl,fr,de,it,es
../map-creator.sh europe/greece ram en,nl,fr,de,it,es
../map-creator.sh europe/guernsey-jersey ram en,nl,fr,de,it,es
../map-creator.sh europe/hungary ram en,nl,fr,de,it,es
../map-creator.sh europe/iceland ram en,nl,fr,de,it,es
../map-creator.sh europe/ireland-and-northern-ireland ram en,nl,fr,de,it,es
../map-creator.sh europe/isle-of-man ram en,nl,fr,de,it,es
../map-creator.sh europe/italy hd en,nl,fr,de,it,es
../map-creator.sh europe/kosovo ram en,nl,fr,de,it,es
../map-creator.sh europe/latvia ram en,nl,fr,de,it,es
../map-creator.sh europe/liechtenstein ram en,nl,fr,de,it,es
../map-creator.sh europe/lithuania ram en,nl,fr,de,it,es
../map-creator.sh europe/luxembourg ram en,nl,fr,de,it,es
../map-creator.sh europe/macedonia ram en,nl,fr,de,it,es
../map-creator.sh europe/malta ram en,nl,fr,de,it,es
../map-creator.sh europe/moldova ram en,nl,fr,de,it,es
../map-creator.sh europe/monaco ram en,nl,fr,de,it,es
../map-creator.sh europe/montenegro ram en,nl,fr,de,it,es
../map-creator.sh europe/netherlands hd en,nl,fr,de,it,es
../map-creator.sh europe/norway hd en,nl,fr,de,it,es
../map-creator.sh europe/poland hd en,nl,fr,de,it,es
../map-creator.sh europe/portugal ram en,nl,fr,de,it,es
../map-creator.sh europe/romania ram en,nl,fr,de,it,es
../map-creator.sh europe/serbia ram en,nl,fr,de,it,es
../map-creator.sh europe/slovakia ram en,nl,fr,de,it,es
../map-creator.sh europe/slovenia ram en,nl,fr,de,it,es
../map-creator.sh europe/spain ram en,nl,fr,de,it,es
../map-creator.sh europe/sweden ram en,nl,fr,de,it,es
../map-creator.sh europe/switzerland ram en,nl,fr,de,it,es
../map-creator.sh europe/turkey ram en,nl,fr,de,it,es
../map-creator.sh europe/ukraine ram en,nl,fr,de,it,es
