#!/bin/bash

cd "$(dirname "$0")"

../map-creator.sh north-america/us/alabama ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/alaska ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/arizona ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/arkansas ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/california ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/colorado ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/connecticut ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/delaware ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/district-of-columbia ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/florida ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/georgia ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/hawaii ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/idaho ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/illinois ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/indiana ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/iowa ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/kansas ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/kentucky ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/louisiana ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/maine ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/maryland ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/massachusetts ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/michigan ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/minnesota ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/mississippi ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/missouri ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/montana ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/nebraska ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/nevada ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/new-hampshire ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/new-jersey ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/new-mexico ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/new-york ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/north-carolina ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/north-dakota ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/ohio ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/oklahoma ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/oregon ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/pennsylvania ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/puerto-rico ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/rhode-island ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/south-carolina ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/south-dakota ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/tennessee ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/texas ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/us-virgin-islands ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/utah ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/vermont ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/virginia ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/washington ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/west-virginia ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/wisconsin ram en,nl,fr,de,it,es
../map-creator.sh north-america/us/wyoming ram en,nl,fr,de,it,es
